### ISSUE TITLE
JIP LN and JG Update Message Appears Even After Updating

### ISSUE THREAD

**Issue by wii-the-dev** [NCRTrooper/The-Courier-Vs.-The-World-FNV#1]
uninstalled and reinstalled NVSE, JIP LN, and Johnny Guitar, yet still get an error popup in-game that I need to update to the newest version of JIP LN even though I just updated

**Comment by NCRTrooper** [comment]
Are you using xNVSE 6.1.6?

**Comment by wii-the-dev** [comment]
yes, I reinstalled NVSE, JIP LN, and Johnny Guitar like I said in the original post

**Comment by NCRTrooper** [comment]
Open the console.

Do these [messages ](https://i.imgur.com/HObZ6ij.jpg)print to the console?

**Comment by NCRTrooper** [comment]
I cannot reproduce this issue. It is likely that JIP LN is failing to load, but there is nothing I can do about that.
